### PR TITLE
Refactor

### LINKED ISSUE #11: Flake8 integration

### LINKED ISSUE #13: Directory clean up

### PR DESCRIPTION
**Pull request by I-question-this**
The purpose of this was to introduce flake8, and make the layers in individual.py an object. Make the layer an object was easy with dataclass, but introducing flake8 resulted in a lot of refactoring of the code. Having standardized code will be worth it in the long run.

closes #11
closes #13

### CODE REVIEW

**Review by king2b3 — DISMISSED** [review]
All looks good to me!

**Comment by king2b3** [comment]
Looks like there is some conflict, I think there is something new in the original indivudal.py that wasn't copied over.

**Comment by king2b3** [comment]
@I-question-this Looks like the conflict can't be solved internally, but go ahead and approve on your side if you'd like. I think the merge conflict is just me removing the stats() method from the individual.py file.

**Comment by I-question-this** [comment]
@king2b3 I was aware of the conflict, and have resolved it. Just got to give me time.

**Comment by king2b3** [comment]
@I-question-this Sounds good, just let me know when you'd like me to review the changes.

**Review by king2b3 — APPROVED** [review]

**Pull request merged**
